import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi';

interface TranslationContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const TranslationContext = createContext<TranslationContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.riskAssessment': 'Risk Assessment',
    'nav.training': 'Training',
    'nav.alerts': 'Alerts',
    'nav.veterinary': 'Veterinary',
    'nav.community': 'Community',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.settings': 'Settings',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.support': 'Support',
    'common.feedback': 'Feedback',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.policy': 'Policy',
    'common.license': 'License',

    // Dashboard
    'dashboard.title': 'Farm Dashboard',
    'dashboard.subtitle': 'Monitor your livestock health and biosecurity',
    'dashboard.farmOnline': 'Farm Online',
    'dashboard.scheduleAssessment': 'Schedule Assessment',
    'dashboard.healthScore': 'Health Score',
    'dashboard.vaccinationRate': 'Vaccination Rate',
    'dashboard.deathsThisMonth': 'Deaths This Month',
    'dashboard.securityCheck': 'Security Check',
    'dashboard.checked': 'Checked',
    'dashboard.of': 'of',
    'dashboard.animals': 'animals',
    'dashboard.normalRange': 'Normal range',
    'dashboard.next': 'Next',
    'dashboard.livestockOverview': 'Livestock Overview',
    'dashboard.poultry': 'Poultry',
    'dashboard.pigs': 'Pigs',
    'dashboard.totalBirds': 'Total Birds',
    'dashboard.lost': 'Lost',
    'dashboard.lastWeek': 'last week',
    'dashboard.healthStatus': 'Health Status',
    'dashboard.healthy': 'Healthy',
    'dashboard.monitorRequired': 'Monitor Required',
    'dashboard.vaccinationProgress': 'Vaccination Progress',
    'dashboard.vaccinated': 'vaccinated',
    'dashboard.biosecurityRiskAssessment': 'Biosecurity Risk Assessment',
    'dashboard.currentRiskLevel': 'Current Risk Level',
    'dashboard.lowRisk': 'Low Risk',
    'dashboard.goodAreas': 'Good Areas',
    'dashboard.watchAreas': 'Watch Areas',
    'dashboard.problemAreas': 'Problem Areas',
    'dashboard.viewFullAssessment': 'View Full Assessment',
    'dashboard.recentActivities': 'Recent Activities',
    'dashboard.fedChickens': 'Fed chickens',
    'dashboard.mainCoop': 'Main coop',
    'dashboard.birds': 'birds',
    'dashboard.checkedPigPen': 'Checked pig pen',
    'dashboard.sectionB': 'Section B',
    'dashboard.cleanedWaterSystems': 'Cleaned water systems',
    'dashboard.allAreas': 'All areas',
    'dashboard.thisMorning': 'This morning',
    'dashboard.yesterday': 'Yesterday',
    'dashboard.daysAgo': 'days ago',
    'dashboard.success': 'success',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.startRiskAssessment': 'Start Risk Assessment',
    'dashboard.logHealthCheck': 'Log Health Check',
    'dashboard.scheduleVaccination': 'Schedule Vaccination',
    'dashboard.reportIssue': 'Report Issue',
    'dashboard.activeAlerts': 'Active Alerts',
    'dashboard.birdFluCases': 'Bird flu cases',
    'dashboard.away': 'away',
    'dashboard.monitorClosely': 'monitor closely',
    'dashboard.needVaccination': 'need vaccination',
    'dashboard.thisWeek': 'this week',
    'dashboard.goodWeather': 'Good weather expected',
    'dashboard.nextDays': 'next 5 days',

    // Training
    'training.title': 'Training Center',
    'training.subtitle': 'Enhance your livestock management skills',
    'training.complete': 'Complete',
    'training.joinLiveSession': 'Join Live Session',
    'training.completed': 'Completed',
    'training.inProgress': 'In Progress',
    'training.certificates': 'Certificates',
    'training.trainingModules': 'Training Modules',
    'training.all': 'All',
    'training.biosecurity': 'Biosecurity',
    'training.health': 'Health',
    'training.emergency': 'Emergency',
    'training.hygiene': 'Hygiene',
    'training.management': 'Management',
    'training.beginner': 'Beginner',
    'training.intermediate': 'Intermediate',
    'training.advanced': 'Advanced',
    'training.progress': 'Progress',
    'training.review': 'Review',
    'training.continue': 'Continue',
    'training.start': 'Start',
    'training.upcomingLiveSessions': 'Upcoming Live Sessions',
    'training.liveQA': 'Live Q&A with veterinary experts',
    'training.tomorrow': 'Tomorrow',
    'training.minutes': 'minutes',
    'training.dr': 'Dr.',
    'training.register': 'Register',
    'training.interactiveWorkshop': 'Interactive workshop on farm assessments',
    'training.friday': 'Friday',

    // Alerts
    'alerts.title': 'Training Alerts',
    'alerts.subtitle': 'Stay informed about livestock health and training updates',
    'alerts.unread': 'Unread',
    'alerts.recentAlerts': 'Recent Alerts',
    'alerts.searchAlerts': 'Search alerts...',
    'alerts.all': 'All',
    'alerts.disease': 'Disease',
    'alerts.vaccines': 'Vaccines',
    'alerts.training': 'Training',
    'alerts.high': 'high',
    'alerts.medium': 'medium',
    'alerts.low': 'low',
    'alerts.acknowledge': 'Acknowledge',
    'alerts.alertSummary': 'Alert Summary',
    'alerts.totalAlerts': 'Total Alerts',
    'alerts.highPriority': 'High Priority',
    'alerts.acknowledged': 'Acknowledged',
    'alerts.notificationSettings': 'Notification Settings',
    'alerts.diseaseOutbreaks': 'Disease Outbreaks',
    'alerts.outbreaksDesc': 'Alerts about disease outbreaks in your area',
    'alerts.vaccinationReminders': 'Vaccination Reminders',
    'alerts.remindersDesc': 'Reminders for scheduled vaccinations',
    'alerts.weatherAlerts': 'Weather Alerts',
    'alerts.weatherDesc': 'Weather conditions affecting livestock',
    'alerts.equipmentMaintenance': 'Equipment Maintenance',
    'alerts.maintenanceDesc': 'Equipment and facility maintenance alerts',
    'alerts.trainingUpdates': 'Training Updates',
    'alerts.updatesDesc': 'New training modules and sessions',
    'alerts.feedQuality': 'Feed Quality',
    'alerts.qualityDesc': 'Feed quality and supply alerts',
    'alerts.upcomingEvents': 'Upcoming Events',
    'alerts.trainingSession': 'Training Session',
    'alerts.diseaseManagement': 'Disease Management Workshop',
    'alerts.vaccinationDue': 'Vaccination Due',
    'alerts.section': 'Section',

    // Veterinary
    'veterinary.title': 'Veterinary Services',
    'veterinary.subtitle': 'Professional veterinary care for your livestock',
    'veterinary.emergencyCall': 'Emergency Call',
    'veterinary.bookAppointment': 'Book Appointment',
    'veterinary.availableServices': 'Available Services',
    'veterinary.virtualConsultation': 'Virtual Consultation',
    'veterinary.consultationDesc': 'Get expert advice from certified veterinarians',
    'veterinary.emergencyVisit': 'Emergency Visit',
    'veterinary.emergencyDesc': 'Urgent veterinary care at your farm',
    'veterinary.vaccinationProgram': 'Vaccination Program',
    'veterinary.vaccinationDesc': 'Comprehensive vaccination schedules',
    'veterinary.perAnimal': 'per animal',
    'veterinary.healthAssessment': 'Health Assessment',
    'veterinary.assessmentDesc': 'Complete livestock health evaluation',
    'veterinary.bookNow': 'Book Now',
    'veterinary.ourVeterinarians': 'Our Veterinarians',
    'veterinary.experience': 'experience',
    'veterinary.reviews': 'reviews',
    'veterinary.available': 'Available',
    'veterinary.chat': 'Chat',
    'veterinary.recentRecords': 'Recent Records',
    'veterinary.viewAllRecords': 'View All Records',
    'veterinary.upcomingAppointments': 'Upcoming Appointments',
    'veterinary.scheduleNew': 'Schedule New',
    'veterinary.emergencyContact': 'Emergency Contact',
    'veterinary.emergencyLine': '24/7 Emergency Line',
    'veterinary.callNow': 'Call Now',
    'veterinary.urgent': 'For urgent livestock health emergencies',

    // Community
    'community.title': 'Community Hub',
    'community.subtitle': 'Connect, learn, and grow with fellow farmers',
    'community.members': 'Members',
    'community.newDiscussion': 'New Discussion',
    'community.communityDiscussions': 'Community Discussions',
    'community.searchDiscussions': 'Search discussions...',
    'community.discussions': 'Discussions',
    'community.askExperts': 'Ask Experts',
    'community.events': 'Events',
    'community.by': 'by',
    'community.hot': 'Hot',
    'community.replies': 'replies',
    'community.likes': 'likes',
    'community.views': 'views',
    'community.reply': 'Reply',
    'community.like': 'Like',
    'community.share': 'Share',
    'community.online': 'Online',
    'community.offline': 'Offline',
    'community.response': 'Response',
    'community.askQuestion': 'Ask Question',
    'community.monthlyFarmer': 'Monthly Farmer Meetup',
    'community.meetupDesc': 'Monthly gathering for local farmers to share experiences and knowledge.',
    'community.communityHall': 'Community Hall, District Center',
    'community.attending': 'attending',
    'community.networking': 'networking',
    'community.biosecurityWorkshop': 'Biosecurity Workshop',
    'community.workshopDesc': 'Learn about latest biosecurity measures and disease prevention strategies.',
    'community.onlineLocation': 'Online (Zoom)',
    'community.workshop': 'workshop',
    'community.qa': 'Q&A',
    'community.qaDesc': 'Q&A session with certification experts about organic farming requirements.',
    'community.agriculturalOffice': 'Agricultural Extension Office',
    'community.joinEvent': 'Join Event',
    'community.communityStats': 'Community Stats',
    'community.activeMembers': 'Active Members',
    'community.discussionsToday': 'Discussions Today',
    'community.questionsAnswered': 'Questions Answered',
    'community.eventsThisMonth': 'Events This Month',
    'community.topContributors': 'Top Contributors',
    'community.answers': 'answers',
    'community.quickActions': 'Quick Actions',
    'community.startDiscussion': 'Start Discussion',
    'community.createEvent': 'Create Event',
    'community.shareKnowledge': 'Share Knowledge',

    // Chatbot
    'chatbot.title': 'AI Assistant',
    'chatbot.subtitle': 'Ask me anything about livestock management',
    'chatbot.welcomeMessage': 'Hello! I\'m your AI farming assistant. How can I help you today?',
    'chatbot.helpText': 'Ask me about livestock health, biosecurity, training, or any farming questions! Click "Test AI" to check if the service is working.',
    'chatbot.placeholder': 'Type your message here...',
    'chatbot.typing': 'AI is typing...',
    'chatbot.clearChat': 'Clear Chat',
    'chatbot.poweredBy': 'Powered by LivSecure',
    'chatbot.errorMessage': 'Sorry, I encountered an error. Please try again.'
  },

  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.riskAssessment': 'जोखिम मूल्यांकन',
    'nav.training': 'प्रशिक्षण',
    'nav.alerts': 'अलर्ट',
    'nav.veterinary': 'पशु चिकित्सा',
    'nav.community': 'समुदाय',

    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.submit': 'सबमिट करें',
    'common.delete': 'मिटाएं',
    'common.edit': 'संपादित करें',
    'common.view': 'देखें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.search': 'खोजें',
    'common.filter': 'फिल्टर',
    'common.sort': 'क्रमबद्ध करें',
    'common.export': 'निर्यात',
    'common.import': 'आयात',
    'common.yes': 'हां',
    'common.no': 'नहीं',
    'common.ok': 'ठीक है',
    'common.close': 'बंद करें',
    'common.open': 'खोलें',
    'common.settings': 'सेटिंग्स',
    'common.help': 'मदद',
    'common.about': 'बारे में',
    'common.contact': 'संपर्क',
    'common.support': 'सहायता',
    'common.feedback': 'प्रतिक्रिया',
    'common.privacy': 'गोपनीयता',
    'common.terms': 'शर्तें',
    'common.policy': 'नीति',
    'common.license': 'लाइसेंस',

    // Dashboard
    'dashboard.title': 'फार्म डैशबोर्ड',
    'dashboard.subtitle': 'अपने पशुधन स्वास्थ्य और जैव सुरक्षा की निगरानी करें',
    'dashboard.farmOnline': 'फार्म ऑनलाइन',
    'dashboard.scheduleAssessment': 'मूल्यांकन निर्धारित करें',
    'dashboard.healthScore': 'स्वास्थ्य स्कोर',
    'dashboard.vaccinationRate': 'टीकाकरण दर',
    'dashboard.deathsThisMonth': 'इस महीने मौतें',
    'dashboard.securityCheck': 'सुरक्षा जांच',
    'dashboard.checked': 'जांच की गई',
    'dashboard.of': 'का',
    'dashboard.animals': 'पशु',
    'dashboard.normalRange': 'सामान्य सीमा',
    'dashboard.next': 'अगला',
    'dashboard.livestockOverview': 'पशुधन अवलोकन',
    'dashboard.poultry': 'मुर्गी पालन',
    'dashboard.pigs': 'सूअर',
    'dashboard.totalBirds': 'कुल पक्षी',
    'dashboard.lost': 'खो गया',
    'dashboard.lastWeek': 'पिछले सप्ताह',
    'dashboard.healthStatus': 'स्वास्थ्य स्थिति',
    'dashboard.healthy': 'स्वस्थ',
    'dashboard.monitorRequired': 'निगरानी आवश्यक',
    'dashboard.vaccinationProgress': 'टीकाकरण प्रगति',
    'dashboard.vaccinated': 'टीकाकरण किया गया',
    'dashboard.biosecurityRiskAssessment': 'जैव सुरक्षा जोखिम मूल्यांकन',
    'dashboard.currentRiskLevel': 'वर्तमान जोखिम स्तर',
    'dashboard.lowRisk': 'कम जोखिम',
    'dashboard.goodAreas': 'अच्छे क्षेत्र',
    'dashboard.watchAreas': 'ध्यान क्षेत्र',
    'dashboard.problemAreas': 'समस्या क्षेत्र',
    'dashboard.viewFullAssessment': 'पूर्ण मूल्यांकन देखें',
    'dashboard.recentActivities': 'हाल की गतिविधियां',
    'dashboard.fedChickens': 'चिकन खिलाया',
    'dashboard.mainCoop': 'मुख्य कूप',
    'dashboard.birds': 'पक्षी',
    'dashboard.checkedPigPen': 'सूअर का बाड़ा जांचा',
    'dashboard.sectionB': 'अनुभाग B',
    'dashboard.cleanedWaterSystems': 'पानी की व्यवस्था साफ की',
    'dashboard.allAreas': 'सभी क्षेत्र',
    'dashboard.thisMorning': 'आज सुबह',
    'dashboard.yesterday': 'कल',
    'dashboard.daysAgo': 'दिन पहले',
    'dashboard.success': 'सफल',
    'dashboard.quickActions': 'त्वरित कार्य',
    'dashboard.startRiskAssessment': 'जोखिम मूल्यांकन शुरू करें',
    'dashboard.logHealthCheck': 'स्वास्थ्य जांच लॉग करें',
    'dashboard.scheduleVaccination': 'टीकाकरण निर्धारित करें',
    'dashboard.reportIssue': 'समस्या रिपोर्ट करें',
    'dashboard.activeAlerts': 'सक्रिय अलर्ट',
    'dashboard.birdFluCases': 'बर्ड फ्लू मामले',
    'dashboard.away': 'दूर',
    'dashboard.monitorClosely': 'निकट से निगरानी करें',
    'dashboard.needVaccination': 'टीकाकरण की आवश्यकता',
    'dashboard.thisWeek': 'इस सप्ताह',
    'dashboard.goodWeather': 'अच्छा मौसम अपेक्षित',
    'dashboard.nextDays': 'अगले 5 दिन',

    // Training
    'training.title': 'प्रशिक्षण केंद्र',
    'training.subtitle': 'अपने पशुधन प्रबंधन कौशल बढ़ाएं',
    'training.complete': 'पूर्ण',
    'training.joinLiveSession': 'लाइव सत्र में शामिल हों',
    'training.completed': 'पूर्ण',
    'training.inProgress': 'प्रगति में',
    'training.certificates': 'प्रमाण पत्र',
    'training.trainingModules': 'प्रशिक्षण मॉड्यूल',
    'training.all': 'सभी',
    'training.biosecurity': 'जैव सुरक्षा',
    'training.health': 'स्वास्थ्य',
    'training.emergency': 'आपातकाल',
    'training.hygiene': 'स्वच्छता',
    'training.management': 'प्रबंधन',
    'training.beginner': 'शुरुआती',
    'training.intermediate': 'मध्यम',
    'training.advanced': 'उन्नत',
    'training.progress': 'प्रगति',
    'training.review': 'समीक्षा',
    'training.continue': 'जारी रखें',
    'training.start': 'शुरू करें',
    'training.upcomingLiveSessions': 'आगामी लाइव सत्र',
    'training.liveQA': 'पशु चिकित्सा विशेषज्ञों के साथ लाइव प्रश्नोत्तर',
    'training.tomorrow': 'कल',
    'training.minutes': 'मिनट',
    'training.dr': 'डॉ.',
    'training.register': 'पंजीकरण करें',
    'training.interactiveWorkshop': 'फार्म मूल्यांकन पर इंटरैक्टिव कार्यशाला',
    'training.friday': 'शुक्रवार',

    // Alerts
    'alerts.title': 'प्रशिक्षण अलर्ट',
    'alerts.subtitle': 'पशुधन स्वास्थ्य और प्रशिक्षण अपडेट के बारे में सूचित रहें',
    'alerts.unread': 'अपठित',
    'alerts.recentAlerts': 'हाल के अलर्ट',
    'alerts.searchAlerts': 'अलर्ट खोजें...',
    'alerts.all': 'सभी',
    'alerts.disease': 'बीमारी',
    'alerts.vaccines': 'टीके',
    'alerts.training': 'प्रशिक्षण',
    'alerts.high': 'उच्च',
    'alerts.medium': 'मध्यम',
    'alerts.low': 'कम',
    'alerts.acknowledge': 'स्वीकार करें',
    'alerts.alertSummary': 'अलर्ट सारांश',
    'alerts.totalAlerts': 'कुल अलर्ट',
    'alerts.highPriority': 'उच्च प्राथमिकता',
    'alerts.acknowledged': 'स्वीकार किया गया',
    'alerts.notificationSettings': 'सूचना सेटिंग्स',
    'alerts.diseaseOutbreaks': 'बीमारी प्रकोप',
    'alerts.outbreaksDesc': 'आपके क्षेत्र में बीमारी प्रकोप के बारे में अलर्ट',
    'alerts.vaccinationReminders': 'टीकाकरण अनुस्मारक',
    'alerts.remindersDesc': 'निर्धारित टीकाकरण के लिए अनुस्मारक',
    'alerts.weatherAlerts': 'मौसम अलर्ट',
    'alerts.weatherDesc': 'पशुधन को प्रभावित करने वाली मौसम स्थितियां',
    'alerts.equipmentMaintenance': 'उपकरण रखरखाव',
    'alerts.maintenanceDesc': 'उपकरण और सुविधा रखरखाव अलर्ट',
    'alerts.trainingUpdates': 'प्रशिक्षण अपडेट',
    'alerts.updatesDesc': 'नए प्रशिक्षण मॉड्यूल और सत्र',
    'alerts.feedQuality': 'चारा गुणवत्ता',
    'alerts.qualityDesc': 'चारा गुणवत्ता और आपूर्ति अलर्ट',
    'alerts.upcomingEvents': 'आगामी कार्यक्रम',
    'alerts.trainingSession': 'प्रशिक्षण सत्र',
    'alerts.diseaseManagement': 'बीमारी प्रबंधन कार्यशाला',
    'alerts.vaccinationDue': 'टीकाकरण देय',
    'alerts.section': 'अनुभाग',

    // Veterinary
    'veterinary.title': 'पशु चिकित्सा सेवाएं',
    'veterinary.subtitle': 'अपने पशुधन के लिए पेशेवर पशु चिकित्सा देखभाल',
    'veterinary.emergencyCall': 'आपातकालीन कॉल',
    'veterinary.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'veterinary.availableServices': 'उपलब्ध सेवाएं',
    'veterinary.virtualConsultation': 'वर्चुअल परामर्श',
    'veterinary.consultationDesc': 'प्रमाणित पशु चिकित्सकों से विशेषज्ञ सलाह प्राप्त करें',
    'veterinary.emergencyVisit': 'आपातकालीन विजिट',
    'veterinary.emergencyDesc': 'आपके फार्म पर तत्काल पशु चिकित्सा देखभाल',
    'veterinary.vaccinationProgram': 'टीकाकरण कार्यक्रम',
    'veterinary.vaccinationDesc': 'व्यापक टीकाकरण कार्यक्रम',
    'veterinary.perAnimal': 'प्रति पशु',
    'veterinary.healthAssessment': 'स्वास्थ्य मूल्यांकन',
    'veterinary.assessmentDesc': 'पूर्ण पशुधन स्वास्थ्य मूल्यांकन',
    'veterinary.bookNow': 'अभी बुक करें',
    'veterinary.ourVeterinarians': 'हमारे पशु चिकित्सक',
    'veterinary.experience': 'अनुभव',
    'veterinary.reviews': 'समीक्षाएं',
    'veterinary.available': 'उपलब्ध',
    'veterinary.chat': 'चैट',
    'veterinary.recentRecords': 'हाल के रिकॉर्ड',
    'veterinary.viewAllRecords': 'सभी रिकॉर्ड देखें',
    'veterinary.upcomingAppointments': 'आगामी अपॉइंटमेंट',
    'veterinary.scheduleNew': 'नया निर्धारित करें',
    'veterinary.emergencyContact': 'आपातकालीन संपर्क',
    'veterinary.emergencyLine': '24/7 आपातकालीन लाइन',
    'veterinary.callNow': 'अभी कॉल करें',
    'veterinary.urgent': 'तत्काल पशुधन स्वास्थ्य आपातकाल के लिए',

    // Community
    'community.title': 'समुदाय केंद्र',
    'community.subtitle': 'साथी किसानों के साथ जुड़ें, सीखें और बढ़ें',
    'community.members': 'सदस्य',
    'community.newDiscussion': 'नई चर्चा',
    'community.communityDiscussions': 'समुदाय चर्चाएं',
    'community.searchDiscussions': 'चर्चाएं खोजें...',
    'community.discussions': 'चर्चाएं',
    'community.askExperts': 'विशेषज्ञों से पूछें',
    'community.events': 'कार्यक्रम',
    'community.by': 'द्वारा',
    'community.hot': 'गर्म',
    'community.replies': 'उत्तर',
    'community.likes': 'पसंद',
    'community.views': 'दृश्य',
    'community.reply': 'उत्तर दें',
    'community.like': 'पसंद करें',
    'community.share': 'साझा करें',
    'community.online': 'ऑनलाइन',
    'community.offline': 'ऑफलाइन',
    'community.response': 'उत्तर',
    'community.askQuestion': 'प्रश्न पूछें',
    'community.monthlyFarmer': 'मासिक किसान मिलन',
    'community.meetupDesc': 'स्थानीय किसानों के लिए अनुभव और ज्ञान साझा करने के लिए मासिक सभा।',
    'community.communityHall': 'समुदाय हॉल, जिला केंद्र',
    'community.attending': 'उपस्थित',
    'community.networking': 'नेटवर्किंग',
    'community.biosecurityWorkshop': 'जैव सुरक्षा कार्यशाला',
    'community.workshopDesc': 'नवीनतम जैव सुरक्षा उपायों और बीमारी रोकथाम रणनीतियों के बारे में जानें।',
    'community.onlineLocation': 'ऑनलाइन (जूम)',
    'community.workshop': 'कार्यशाला',
    'community.qa': 'प्रश्नोत्तर',
    'community.qaDesc': 'जैविक खेती आवश्यकताओं के बारे में प्रमाणन विशेषज्ञों के साथ प्रश्नोत्तर सत्र।',
    'community.agriculturalOffice': 'कृषि विस्तार कार्यालय',
    'community.joinEvent': 'कार्यक्रम में शामिल हों',
    'community.communityStats': 'समुदाय आंकड़े',
    'community.activeMembers': 'सक्रिय सदस्य',
    'community.discussionsToday': 'आज की चर्चाएं',
    'community.questionsAnswered': 'उत्तर दिए गए प्रश्न',
    'community.eventsThisMonth': 'इस महीने के कार्यक्रम',
    'community.topContributors': 'शीर्ष योगदानकर्ता',
    'community.answers': 'उत्तर',
    'community.quickActions': 'त्वरित कार्य',
    'community.startDiscussion': 'चर्चा शुरू करें',
    'community.createEvent': 'कार्यक्रम बनाएं',
    'community.shareKnowledge': 'ज्ञान साझा करें',

    // Chatbot
    'chatbot.title': 'AI सहायक',
    'chatbot.subtitle': 'पशुधन प्रबंधन के बारे में कुछ भी पूछें',
    'chatbot.welcomeMessage': 'नमस्ते! मैं आपका AI कृषि सहायक हूं। आज मैं आपकी कैसे मदद कर सकता हूं?',
    'chatbot.helpText': 'मुझे पशुधन स्वास्थ्य, जैव सुरक्षा, प्रशिक्षण, या कोई भी कृषि प्रश्न पूछें! "Test AI" पर क्लिक करके जांचें कि सेवा काम कर रही है या नहीं।',
    'chatbot.placeholder': 'अपना संदेश यहां टाइप करें...',
    'chatbot.typing': 'AI टाइप कर रहा है...',
    'chatbot.clearChat': 'चैट साफ करें',
    'chatbot.poweredBy': 'द्वारा संचालित LivSecure',
    'chatbot.errorMessage': 'क्षमा करें, मुझे एक त्रुटि का सामना करना पड़ा। कृपया पुनः प्रयास करें।'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'hi')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <TranslationContext.Provider value={{ language, setLanguage: handleLanguageChange, t }}>
      {children}
    </TranslationContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(TranslationContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
}